# Generated by Django 5.1.4 on 2024-12-31 11:48
import uuid
from django.db import migrations, models
from django.core.validators import EmailValidator, MinLengthValidator, MaxLengthValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[MaxLengthValidator(100)])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[EmailValidator(), MaxLengthValidator(255)])),
                ('icon_color', models.CharField(max_length=6, validators=[MinLengthValidator(6), MaxLengthValidator(6)])),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
